const ac = {
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',

    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

    LOG_OUT: 'LOG_OUT',

    //------------------------------------------------------------------------//

    GET_BOARD_START: 'GET_BOARD_START',
    GET_BOARD_SUCCESS: 'GET_BOARD_SUCCESS',
    GET_BOARD_ERROR: 'GET_BOARD_ERROR',

    CREATE_BOARD_START: 'CREATE_BOARD_START',
    CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
    CREATE_BOARD_ERROR: 'CREATE_BOARD_ERROR',

    REMOVE_BOARD_START: 'REMOVE_BOARD_START',
    REMOVE_BOARD_SUCCESS: 'REMOVE_BOARD_SUCCESS',
    REMOVE_BOARD_ERROR: 'REMOVE_BOARD_ERROR',

    CREATE_BOARD_SYNC: 'CREATE_BOARD_SYNC',
    REMOVE_BOARD_SYNC: 'REMOVE_BOARD_SYNC',

    //------------------------------------------------------------------------//

    GET_CARD_START: 'GET_CARD_START',
    GET_CARD_SUCCESS: 'GET_CARD_SUCCESS',
    GET_CARD_ERROR: 'GET_CARD_ERROR',

    CREATE_CARD_START: 'CREATE_CARD_START',
    CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
    CREATE_CARD_ERROR: 'CREATE_CARD_ERROR',

    REMOVE_CARD_START: 'REMOVE_CARD_START',
    REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',
    REMOVE_CARD_ERROR: 'REMOVE_CARD_ERROR',

    CREATE_CARD_SYNC: 'CREATE_CARD_SYNC',
    REMOVE_CARD_SYNC: 'REMOVE_CARD_SYNC',

    //------------------------------------------------------------------------//

    CREATE_TASK_START: 'CREATE_TASK_START',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

    REMOVE_TASK_START: 'REMOVE_TASK_START',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
    REMOVE_TASK_ERROR: 'REMOVE_TASK_ERROR',

    CREATE_TASK_SYNC: 'CREATE_TASK_SYNC',
    REMOVE_TASK_SYNC: 'REMOVE_TASK_SYNC',

}

export default ac;
